# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
analyzer:
  
  
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    avoid_type_to_string: true
    close_sinks: true
    comment_references: true
    require_trailing_commas: true
    deprecated_member_use_from_same_package: true
    literal_only_boolean_expressions: true
    missing_code_block_language_in_doc_comment: true
    no_adjacent_strings_in_list: true
    always_put_required_named_parameters_first: true
    always_put_control_body_on_new_line: true
    always_declare_return_types: true
    unnecessary_statements: true
    throw_in_finally: true
    test_types_in_equals: true
    prefer_void_to_null: true
    always_require_non_null_named_parameters: true
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_double_and_int_checks: true
    avoid_final_parameters: true
    avoid_private_typedef_functions: true
    avoid_returning_this: true
    avoid_types_on_closure_parameters: false
    avoid_setters_without_getters: true
    cascade_invocations: true
    conditional_uri_does_not_exist: true
    eol_at_end_of_file: true
    directives_ordering: true
    deprecated_consistency: true
    combinators_ordering: true
    cast_nullable_to_non_nullable: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    avoid_redundant_argument_values: true
    avoid_multiple_declarations_per_line: true
    avoid_js_rounded_ints: true
    avoid_implementing_value_types: true
    avoid_field_initializers_in_const_classes: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_catching_errors: true
    avoid_escaping_inner_quotes: true
    flutter_style_todos: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_names: true
    matching_super_parameters: true
    missing_whitespace_between_adjacent_strings: true
    no_literal_bool_comparisons: true
    no_runtimeType_toString: true
    noop_primitive_operations: true
    omit_local_variable_types: true
    only_throw_errors: true
    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_final_in_for_each: true
    prefer_constructors_over_static_methods: true
    prefer_asserts_with_message: true
    prefer_asserts_in_initializer_lists: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_parenthesis: true
    unreachable_from_main: true
    unnecessary_raw_strings: true
    use_colored_box: true
    use_to_and_as_if_applicable: true
    prefer_int_literals: true
    unnecessary_library_name: true
    unnecessary_library_directive: true
    unnecessary_lambdas: true
    prefer_final_locals: true
    unnecessary_breaks: true
    type_annotate_public_apis: true
    tighten_type_of_initializing_formals: true
    sort_unnamed_constructors_first: true
    sort_constructors_first: true
    sized_box_shrink_expand: true
    
    prefer_null_aware_method_calls: true
    prefer_mixin: true
    use_decorated_box: true
    use_enums: true
    use_test_throws_matchers: true
    use_string_buffers: true
    use_setters_to_change_properties: true
    use_raw_strings: true
    use_named_constants: true
    use_is_even_rather_than_modulo: true
    use_if_null_to_convert_nulls_to_bools: true
# Additional information about this file can be found at
# https://dart.dev/tools/analysis
